---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-proxy-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-proxy-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-proxy-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: log-proxy-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: log-proxy-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      serviceAccountName: log-proxy-sa
      containers:
      - name: inference-server
        image: vllm/vllm-openai:v0.7.3
        command: [ "/bin/sh", "-c" ]
        args: [ "vllm serve unsloth/Meta-Llama-3.1-8B-Instruct --host=0.0.0.0 --port=8000 --dtype=bfloat16 --max-model-len 8192 --disable-log-stats" ]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "2"
            memory: "10Gi"
            ephemeral-storage: "50Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "2"
            memory: "10Gi"
            ephemeral-storage: "50Gi"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: app-volume
          mountPath: /app
      - name: vllm-token-stats
        image: dganochenko/vllm-token-stats:1:0
        resources:
          requests:
            cpu: 500m
            memory: "512Mi"
          limits:
            cpu: 500m
            memory: "512Mi"
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
        cloud.google.com/gke-gpu-driver-version: latest
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-endpoint
spec:
  selector:
    app: vllm
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: vllm
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: proxy
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: vllm-token-stats
spec:
  selector:
    matchLabels:
      app: vllm  
  endpoints:
  - port: 3000
    interval: 30s
    path: /metrics
